title: 정기's 개발 블로그
description: "재미있는 일을 찾아서..."
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: pjk3665@naver.com
github_username: parkjungg
instagram_username: jg_giig

# External API
giscus_repo: "parkjungg/parkjungg.github.io"
giscus_repoId: "R_kgDOQz9ywA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOQz9ywM4C0oQD"
goatcounter_code: parkjungg
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
